package com.hxxCommunity.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hxxCommunity.models.XxdCommColor;

public class XxdCommColorSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_color
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCommColor record) {
        BEGIN();
        INSERT_INTO("comm_color");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getColorId() != null) {
            VALUES("color_id", "#{colorId,jdbcType=VARCHAR}");
        }
        
        if (record.getColorName() != null) {
            VALUES("color_name", "#{colorName,jdbcType=VARCHAR}");
        }
        
        if (record.getColorRgb() != null) {
            VALUES("color_rgb", "#{colorRgb,jdbcType=VARCHAR}");
        }
        
        if (record.getColorState() != null) {
            VALUES("color_state", "#{colorState,jdbcType=CHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_color
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCommColor record) {
        BEGIN();
        UPDATE("comm_color");
        
        if (record.getColorId() != null) {
            SET("color_id = #{colorId,jdbcType=VARCHAR}");
        }
        
        if (record.getColorName() != null) {
            SET("color_name = #{colorName,jdbcType=VARCHAR}");
        }
        
        if (record.getColorRgb() != null) {
            SET("color_rgb = #{colorRgb,jdbcType=VARCHAR}");
        }
        
        if (record.getColorState() != null) {
            SET("color_state = #{colorState,jdbcType=CHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}