package com.hxxCommunity.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hxxCommunity.models.XxdCommShopServiceSpu;

public class XxdCommShopServiceSpuSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_shop_service_spu
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCommShopServiceSpu record) {
        BEGIN();
        INSERT_INTO("comm_shop_service_spu");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getGoodId() != null) {
            VALUES("good_id", "#{goodId,jdbcType=INTEGER}");
        }
        
        if (record.getSpuId() != null) {
            VALUES("spu_id", "#{spuId,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_shop_service_spu
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCommShopServiceSpu record) {
        BEGIN();
        UPDATE("comm_shop_service_spu");
        
        if (record.getGoodId() != null) {
            SET("good_id = #{goodId,jdbcType=INTEGER}");
        }
        
        if (record.getSpuId() != null) {
            SET("spu_id = #{spuId,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}