package com.hxxCommunity.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hxxCommunity.models.XxdCommEmnuInfo;

public class XxdCommEmnuInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_emnu_info
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCommEmnuInfo record) {
        BEGIN();
        INSERT_INTO("comm_emnu_info");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getEmnuId() != null) {
            VALUES("emnu_id", "#{emnuId,jdbcType=VARCHAR}");
        }
        
        if (record.getEmnuValue() != null) {
            VALUES("emnu_value", "#{emnuValue,jdbcType=VARCHAR}");
        }
        
        if (record.getEmnuState() != null) {
            VALUES("emnu_state", "#{emnuState,jdbcType=CHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_emnu_info
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCommEmnuInfo record) {
        BEGIN();
        UPDATE("comm_emnu_info");
        
        if (record.getEmnuId() != null) {
            SET("emnu_id = #{emnuId,jdbcType=VARCHAR}");
        }
        
        if (record.getEmnuValue() != null) {
            SET("emnu_value = #{emnuValue,jdbcType=VARCHAR}");
        }
        
        if (record.getEmnuState() != null) {
            SET("emnu_state = #{emnuState,jdbcType=CHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}