package com.hxxCommunity.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.hxxCommunity.models.XxdCommSpuValue;

public class XxdCommSpuValueSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_spu_value
     *
     * @mbggenerated
     */
    public String insertSelective(XxdCommSpuValue record) {
        BEGIN();
        INSERT_INTO("comm_spu_value");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getSpuId() != null) {
            VALUES("spu_id", "#{spuId,jdbcType=INTEGER}");
        }
        
        if (record.getVal() != null) {
            VALUES("val", "#{val,jdbcType=VARCHAR}");
        }
        
        if (record.getStat() != null) {
            VALUES("stat", "#{stat,jdbcType=CHAR}");
        }
        
        if (record.getSortNo() != null) {
            VALUES("sort_no", "#{sortNo,jdbcType=SMALLINT}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_spu_value
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdCommSpuValue record) {
        BEGIN();
        UPDATE("comm_spu_value");
        
        if (record.getSpuId() != null) {
            SET("spu_id = #{spuId,jdbcType=INTEGER}");
        }
        
        if (record.getVal() != null) {
            SET("val = #{val,jdbcType=VARCHAR}");
        }
        
        if (record.getStat() != null) {
            SET("stat = #{stat,jdbcType=CHAR}");
        }
        
        if (record.getSortNo() != null) {
            SET("sort_no = #{sortNo,jdbcType=SMALLINT}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}