package com.hxxCommunity.models;

public class XxdCommSpuValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu_value.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu_value.spu_id
     *
     * @mbggenerated
     */
    private Integer spuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu_value.val
     *
     * @mbggenerated
     */
    private String val;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu_value.stat
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu_value.sort_no
     *
     * @mbggenerated
     */
    private Short sortNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu_value.id
     *
     * @return the value of comm_spu_value.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu_value.id
     *
     * @param id the value for comm_spu_value.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu_value.spu_id
     *
     * @return the value of comm_spu_value.spu_id
     *
     * @mbggenerated
     */
    public Integer getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu_value.spu_id
     *
     * @param spuId the value for comm_spu_value.spu_id
     *
     * @mbggenerated
     */
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu_value.val
     *
     * @return the value of comm_spu_value.val
     *
     * @mbggenerated
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu_value.val
     *
     * @param val the value for comm_spu_value.val
     *
     * @mbggenerated
     */
    public void setVal(String val) {
        this.val = val == null ? null : val.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu_value.stat
     *
     * @return the value of comm_spu_value.stat
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu_value.stat
     *
     * @param stat the value for comm_spu_value.stat
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu_value.sort_no
     *
     * @return the value of comm_spu_value.sort_no
     *
     * @mbggenerated
     */
    public Short getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu_value.sort_no
     *
     * @param sortNo the value for comm_spu_value.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Short sortNo) {
        this.sortNo = sortNo;
    }
}