package com.hxxCommunity.models;

public class XxdCommShopServiceSpu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_shop_service_spu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_shop_service_spu.good_id
     *
     * @mbggenerated
     */
    private Integer goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_shop_service_spu.spu_id
     *
     * @mbggenerated
     */
    private Integer spuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_shop_service_spu.id
     *
     * @return the value of comm_shop_service_spu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_shop_service_spu.id
     *
     * @param id the value for comm_shop_service_spu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_shop_service_spu.good_id
     *
     * @return the value of comm_shop_service_spu.good_id
     *
     * @mbggenerated
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_shop_service_spu.good_id
     *
     * @param goodId the value for comm_shop_service_spu.good_id
     *
     * @mbggenerated
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_shop_service_spu.spu_id
     *
     * @return the value of comm_shop_service_spu.spu_id
     *
     * @mbggenerated
     */
    public Integer getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_shop_service_spu.spu_id
     *
     * @param spuId the value for comm_shop_service_spu.spu_id
     *
     * @mbggenerated
     */
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }
}