package com.hxxCommunity.models;

public class XxdCommSpu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.parentid
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.childid
     *
     * @mbggenerated
     */
    private Integer childid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.iscolor
     *
     * @mbggenerated
     */
    private String iscolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.isenum
     *
     * @mbggenerated
     */
    private String isenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.isinput
     *
     * @mbggenerated
     */
    private String isinput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.isprimary
     *
     * @mbggenerated
     */
    private String isprimary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.issale
     *
     * @mbggenerated
     */
    private String issale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.stat
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_spu.sort_no
     *
     * @mbggenerated
     */
    private Short sortNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.id
     *
     * @return the value of comm_spu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.id
     *
     * @param id the value for comm_spu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.name
     *
     * @return the value of comm_spu.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.name
     *
     * @param name the value for comm_spu.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.parentid
     *
     * @return the value of comm_spu.parentid
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.parentid
     *
     * @param parentid the value for comm_spu.parentid
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.childid
     *
     * @return the value of comm_spu.childid
     *
     * @mbggenerated
     */
    public Integer getChildid() {
        return childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.childid
     *
     * @param childid the value for comm_spu.childid
     *
     * @mbggenerated
     */
    public void setChildid(Integer childid) {
        this.childid = childid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.iscolor
     *
     * @return the value of comm_spu.iscolor
     *
     * @mbggenerated
     */
    public String getIscolor() {
        return iscolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.iscolor
     *
     * @param iscolor the value for comm_spu.iscolor
     *
     * @mbggenerated
     */
    public void setIscolor(String iscolor) {
        this.iscolor = iscolor == null ? null : iscolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.isenum
     *
     * @return the value of comm_spu.isenum
     *
     * @mbggenerated
     */
    public String getIsenum() {
        return isenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.isenum
     *
     * @param isenum the value for comm_spu.isenum
     *
     * @mbggenerated
     */
    public void setIsenum(String isenum) {
        this.isenum = isenum == null ? null : isenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.isinput
     *
     * @return the value of comm_spu.isinput
     *
     * @mbggenerated
     */
    public String getIsinput() {
        return isinput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.isinput
     *
     * @param isinput the value for comm_spu.isinput
     *
     * @mbggenerated
     */
    public void setIsinput(String isinput) {
        this.isinput = isinput == null ? null : isinput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.isprimary
     *
     * @return the value of comm_spu.isprimary
     *
     * @mbggenerated
     */
    public String getIsprimary() {
        return isprimary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.isprimary
     *
     * @param isprimary the value for comm_spu.isprimary
     *
     * @mbggenerated
     */
    public void setIsprimary(String isprimary) {
        this.isprimary = isprimary == null ? null : isprimary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.issale
     *
     * @return the value of comm_spu.issale
     *
     * @mbggenerated
     */
    public String getIssale() {
        return issale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.issale
     *
     * @param issale the value for comm_spu.issale
     *
     * @mbggenerated
     */
    public void setIssale(String issale) {
        this.issale = issale == null ? null : issale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.stat
     *
     * @return the value of comm_spu.stat
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.stat
     *
     * @param stat the value for comm_spu.stat
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_spu.sort_no
     *
     * @return the value of comm_spu.sort_no
     *
     * @mbggenerated
     */
    public Short getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_spu.sort_no
     *
     * @param sortNo the value for comm_spu.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Short sortNo) {
        this.sortNo = sortNo;
    }
}