package com.hxxCommunity.models;

public class XxdCommEmnuInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_emnu_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_emnu_info.emnu_id
     *
     * @mbggenerated
     */
    private String emnuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_emnu_info.emnu_value
     *
     * @mbggenerated
     */
    private String emnuValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_emnu_info.emnu_state
     *
     * @mbggenerated
     */
    private String emnuState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_emnu_info.id
     *
     * @return the value of comm_emnu_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_emnu_info.id
     *
     * @param id the value for comm_emnu_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_emnu_info.emnu_id
     *
     * @return the value of comm_emnu_info.emnu_id
     *
     * @mbggenerated
     */
    public String getEmnuId() {
        return emnuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_emnu_info.emnu_id
     *
     * @param emnuId the value for comm_emnu_info.emnu_id
     *
     * @mbggenerated
     */
    public void setEmnuId(String emnuId) {
        this.emnuId = emnuId == null ? null : emnuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_emnu_info.emnu_value
     *
     * @return the value of comm_emnu_info.emnu_value
     *
     * @mbggenerated
     */
    public String getEmnuValue() {
        return emnuValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_emnu_info.emnu_value
     *
     * @param emnuValue the value for comm_emnu_info.emnu_value
     *
     * @mbggenerated
     */
    public void setEmnuValue(String emnuValue) {
        this.emnuValue = emnuValue == null ? null : emnuValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_emnu_info.emnu_state
     *
     * @return the value of comm_emnu_info.emnu_state
     *
     * @mbggenerated
     */
    public String getEmnuState() {
        return emnuState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_emnu_info.emnu_state
     *
     * @param emnuState the value for comm_emnu_info.emnu_state
     *
     * @mbggenerated
     */
    public void setEmnuState(String emnuState) {
        this.emnuState = emnuState == null ? null : emnuState.trim();
    }
}