package com.hxxCommunity.models;

public class XxdCommGoodClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_good_class.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_good_class.classid
     *
     * @mbggenerated
     */
    private String classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_good_class.classname
     *
     * @mbggenerated
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_good_class.parentid
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_good_class.sort_no
     *
     * @mbggenerated
     */
    private Short sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_good_class.isparent
     *
     * @mbggenerated
     */
    private String isparent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_good_class.id
     *
     * @return the value of comm_good_class.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_good_class.id
     *
     * @param id the value for comm_good_class.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_good_class.classid
     *
     * @return the value of comm_good_class.classid
     *
     * @mbggenerated
     */
    public String getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_good_class.classid
     *
     * @param classid the value for comm_good_class.classid
     *
     * @mbggenerated
     */
    public void setClassid(String classid) {
        this.classid = classid == null ? null : classid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_good_class.classname
     *
     * @return the value of comm_good_class.classname
     *
     * @mbggenerated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_good_class.classname
     *
     * @param classname the value for comm_good_class.classname
     *
     * @mbggenerated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_good_class.parentid
     *
     * @return the value of comm_good_class.parentid
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_good_class.parentid
     *
     * @param parentid the value for comm_good_class.parentid
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_good_class.sort_no
     *
     * @return the value of comm_good_class.sort_no
     *
     * @mbggenerated
     */
    public Short getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_good_class.sort_no
     *
     * @param sortNo the value for comm_good_class.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Short sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_good_class.isparent
     *
     * @return the value of comm_good_class.isparent
     *
     * @mbggenerated
     */
    public String getIsparent() {
        return isparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_good_class.isparent
     *
     * @param isparent the value for comm_good_class.isparent
     *
     * @mbggenerated
     */
    public void setIsparent(String isparent) {
        this.isparent = isparent == null ? null : isparent.trim();
    }
}