package com.hxxCommunity.models;

public class XxdCommColor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_color.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_color.color_id
     *
     * @mbggenerated
     */
    private String colorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_color.color_name
     *
     * @mbggenerated
     */
    private String colorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_color.color_rgb
     *
     * @mbggenerated
     */
    private String colorRgb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_color.color_state
     *
     * @mbggenerated
     */
    private String colorState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_color.id
     *
     * @return the value of comm_color.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_color.id
     *
     * @param id the value for comm_color.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_color.color_id
     *
     * @return the value of comm_color.color_id
     *
     * @mbggenerated
     */
    public String getColorId() {
        return colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_color.color_id
     *
     * @param colorId the value for comm_color.color_id
     *
     * @mbggenerated
     */
    public void setColorId(String colorId) {
        this.colorId = colorId == null ? null : colorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_color.color_name
     *
     * @return the value of comm_color.color_name
     *
     * @mbggenerated
     */
    public String getColorName() {
        return colorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_color.color_name
     *
     * @param colorName the value for comm_color.color_name
     *
     * @mbggenerated
     */
    public void setColorName(String colorName) {
        this.colorName = colorName == null ? null : colorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_color.color_rgb
     *
     * @return the value of comm_color.color_rgb
     *
     * @mbggenerated
     */
    public String getColorRgb() {
        return colorRgb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_color.color_rgb
     *
     * @param colorRgb the value for comm_color.color_rgb
     *
     * @mbggenerated
     */
    public void setColorRgb(String colorRgb) {
        this.colorRgb = colorRgb == null ? null : colorRgb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_color.color_state
     *
     * @return the value of comm_color.color_state
     *
     * @mbggenerated
     */
    public String getColorState() {
        return colorState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_color.color_state
     *
     * @param colorState the value for comm_color.color_state
     *
     * @mbggenerated
     */
    public void setColorState(String colorState) {
        this.colorState = colorState == null ? null : colorState.trim();
    }
}